"""
PostgreSQL + LangChain SQL Agent with Full Execution Pipeline
Pipeline: User → LLM → SQL Text → LangChain Executor → PostgreSQL → Result → LLM → Natural Language Answer

This script ensures:
1. SQL queries are GENERATED by LLM
2. SQL queries are EXECUTED by LangChain executor
3. Results are RETURNED and formatted
4. Final answer is given in NATURAL LANGUAGE
"""

import logging
from pathlib import Path
from typing import Optional, Dict, Any
import sys

# Core imports
import pandas as pd
from langchain_ollama import ChatOllama
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent
from langchain_classic.agents.agent import AgentExecutor

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - [%(levelname)s] - %(message)s'
)
logger = logging.getLogger(__name__)

# ============================================================================
# 1. DATABASE CONNECTION & VALIDATION
# ============================================================================

class PostgreSQLConnection:
    """Handle PostgreSQL connection with proper error handling"""
    
    def __init__(self, 
                 host: str = "localhost",
                 port: int = 5432,
                 user: str = "postgres",
                 password: str = "postgres",
                 database: str = "postgres"):
        """
        Initialize PostgreSQL connection
        
        Args:
            host: Database host (default: localhost)
            port: Database port (default: 5432)
            user: Database user
            password: Database password
            database: Database name
        """
        self.host = host
        self.port = port
        self.user = user
        self.password = password
        self.database = database
        self.connection_string = None
        self.db = None
    
    def build_connection_string(self) -> str:
        """Build PostgreSQL connection string"""
        self.connection_string = (
            f"postgresql://{self.user}:{self.password}@"
            f"{self.host}:{self.port}/{self.database}"
        )
        return self.connection_string
    
    def connect(self, table_names: Optional[list] = None) -> SQLDatabase:
        """
        Connect to PostgreSQL database
        
        Args:
            table_names: List of specific tables to include (optional)
        
        Returns:
            SQLDatabase object for LangChain
        """
        try:
            self.build_connection_string()
            logger.info(f"Connecting to PostgreSQL: {self.host}:{self.port}/{self.database}")
            
            # Create SQLDatabase connection
            if table_names:
                self.db = SQLDatabase.from_uri(
                    self.connection_string,
                    include_tables=table_names
                )
                logger.info(f"Connected to tables: {table_names}")
            else:
                self.db = SQLDatabase.from_uri(self.connection_string)
                logger.info("Connected to database (all tables available)")
            
            # Test connection
            self._test_connection()
            return self.db
        
        except Exception as e:
            logger.error(f"Failed to connect to PostgreSQL: {e}")
            raise
    
    def _test_connection(self):
        """Test database connection by running simple query"""
        try:
            result = self.db.run("SELECT 1")
            logger.info("✅ Database connection test passed")
        except Exception as e:
            logger.error(f"❌ Database connection test failed: {e}")
            raise
    
    def get_tables(self) -> list:
        """Get list of all available tables"""
        try:
            tables = self.db.get_usable_table_names()
            logger.info(f"Available tables: {tables}")
            return tables
        except Exception as e:
            logger.error(f"Failed to get table list: {e}")
            return []
    
    def get_schema(self, table_name: str) -> str:
        """Get schema information for a table"""
        try:
            schema = self.db.get_table_info([table_name])
            logger.info(f"Schema for {table_name}:\n{schema}")
            return schema
        except Exception as e:
            logger.error(f"Failed to get schema for {table_name}: {e}")
            return ""

# ============================================================================
# 2. LANGCHAIN SQL AGENT SETUP
# ============================================================================

class SQLAgent:
    """
    LangChain SQL Agent with full execution pipeline
    Ensures queries are not just generated but EXECUTED
    """
    
    def __init__(self, 
                 db: SQLDatabase,
                 model: str = "llama3.2:1b",
                 temperature: float = 0,
                 verbose: bool = True):
        """
        Initialize SQL Agent
        
        Args:
            db: SQLDatabase connection object
            model: Ollama model (llama3.2:3b recommended, not 1b)
            temperature: LLM temperature (0 = deterministic)
            verbose: Show agent reasoning steps
        """
        self.db = db
        self.model_name = model
        self.temperature = temperature
        self.verbose = verbose
        self.agent_executor = None
        self.llm = None
    
    def setup(self) -> AgentExecutor:
        """
        Setup LLM and SQL Agent Executor
        
        Returns:
            Configured AgentExecutor (this is what EXECUTES queries)
        """
        try:
            logger.info(f"Initializing LLM: {self.model_name}")
            
            # Initialize LLM
            self.llm = ChatOllama(
                model=self.model_name,
                temperature=self.temperature,
                num_predict=512,  # Max output tokens
                top_p=0.95,
                top_k=40
            )
            logger.info("✅ LLM initialized")
            
            # Create SYSTEM PROMPT for better accuracy
            system_prompt = """You are an expert SQL database assistant.
            
CRITICAL RULES:
1. ALWAYS generate VALID PostgreSQL queries
2. NEVER explain, ONLY execute
3. Use table aliases for clarity
4. Always filter unnecessary rows
5. Use aggregate functions when appropriate
6. Format results clearly
7. Handle NULL values appropriately

When given a question, ALWAYS use the available tools to:
1. First, understand the table structure
2. Then, write the SQL query
3. Finally, execute it and return results

Respond ONLY with the query results, no explanations."""
            
            # Create SQL Agent Executor
            # THIS is what actually EXECUTES the queries!
            self.agent_executor = create_sql_agent(
                llm=self.llm,
                db=self.db,
                agent_type="tool-calling",  # Important: must be tool-calling
                verbose=self.verbose,
                system_prompt=system_prompt,
                handle_parsing_errors=True,  # Graceful error handling
                max_iterations=5  # Prevent infinite loops
            )
            
            logger.info("✅ SQL Agent Executor created and ready")
            logger.info(f"Verbose mode: {self.verbose}")
            
            return self.agent_executor
        
        except Exception as e:
            logger.error(f"Failed to setup agent: {e}")
            raise
    
    def query(self, user_input: str) -> Dict[str, Any]:
        """
        Execute a natural language query
        
        This is the COMPLETE PIPELINE:
        User Input → LLM generates SQL → Executor runs SQL → Database returns results → 
        LLM formats answer → Natural Language output
        
        Args:
            user_input: Natural language question
        
        Returns:
            Dictionary with output and intermediate steps
        """
        if not self.agent_executor:
            raise RuntimeError("Agent not initialized. Call setup() first.")
        
        try:
            logger.info(f"\n{'='*70}")
            logger.info(f"User Query: {user_input}")
            logger.info(f"{'='*70}")
            
            # INVOKE THE AGENT
            # This triggers the full pipeline:
            # 1. LLM reads user input
            # 2. LLM generates SQL (tool call)
            # 3. Executor runs the SQL on PostgreSQL
            # 4. Results come back
            # 5. LLM formats natural language response
            response = self.agent_executor.invoke(
                {"input": user_input},
                return_only_outputs=False  # See all intermediate steps
            )
            
            logger.info(f"\n{'='*70}")
            logger.info("FINAL ANSWER:")
            logger.info(f"{'='*70}")
            logger.info(response.get("output", "No output"))
            
            return response
        
        except Exception as e:
            logger.error(f"Query execution failed: {e}")
            logger.error("This usually means:")
            logger.error("  1. SQL syntax error in generated query")
            logger.error("  2. Table/column name mismatch")
            logger.error("  3. Database connection issue")
            logger.error("  4. LLM hallucinated a non-existent table")
            raise

# ============================================================================
# 3. HELPER FUNCTIONS
# ============================================================================

def test_with_sample_data():
    """Test setup with PostgreSQL sample (requires data in database)"""
    
    logger.info("\n" + "="*70)
    logger.info("TESTING SQL AGENT WITH POSTGRESQL")
    logger.info("="*70)
    
    # CONNECTION PARAMETERS - MODIFY FOR YOUR DATABASE
    conn = PostgreSQLConnection(
        host="localhost",        # Your pgAdmin host
        port=5432,               # Default PostgreSQL port
        user="postgres",         # Your pgAdmin username
        password="postgres",     # Your pgAdmin password
        database="postgres"      # Your database name
    )
    
    try:
        # Step 1: Connect to database
        logger.info("\n[STEP 1] Connecting to PostgreSQL...")
        db = conn.connect()
        
        # Step 2: Get available tables
        logger.info("\n[STEP 2] Getting table information...")
        tables = conn.get_tables()
        
        if not tables:
            logger.warning("⚠️ No tables found in database!")
            logger.info("Please create test data first:")
            logger.info("""
            CREATE TABLE sales (
                id SERIAL PRIMARY KEY,
                date DATE,
                product VARCHAR(100),
                category VARCHAR(50),
                sales DECIMAL(10, 2),
                profit DECIMAL(10, 2),
                region VARCHAR(50)
            );
            """)
            return
        
        # Step 3: Show schema for first table
        if tables:
            logger.info(f"\n[STEP 3] Schema for table '{tables[0]}':")
            conn.get_schema(tables[0])
        
        # Step 4: Initialize SQL Agent
        logger.info("\n[STEP 4] Initializing SQL Agent...")
        agent = SQLAgent(
            db=db,
            model="llama3.2:3b",  # Changed from 1b!
            temperature=0,
            verbose=True
        )
        executor = agent.setup()
        
        # Step 5: Test queries (ADAPT THESE TO YOUR TABLES)
        logger.info("\n[STEP 5] Running test queries...")
        
        test_queries = [
            "What tables do I have in this database?",
            "Show me the first 5 records from the sales table",
            "What is the total profit by region?",
            "Which product has the highest average sales?",
        ]
        
        for query in test_queries:
            logger.info(f"\n{'─'*70}")
            try:
                result = agent.query(query)
                print("\n" + result.get("output", "No result"))
            except Exception as e:
                logger.error(f"Query failed: {query}")
                logger.error(f"Error: {e}")
        
    except Exception as e:
        logger.error(f"Test failed: {e}")
        logger.error("\n⚠️ TROUBLESHOOTING:")
        logger.error("1. Ensure PostgreSQL is running")
        logger.error("2. Check pgAdmin connection parameters (host, port, user, password)")
        logger.error("3. Verify Ollama is running: ollama serve")
        logger.error("4. Check model is installed: ollama pull llama3.2:3b")
        logger.error("5. Ensure database has tables with data")

# ============================================================================
# 4. DIRECT SQL FALLBACK (NO LLM, JUST EXECUTE)
# ============================================================================

def execute_sql_directly(db: SQLDatabase, sql_query: str) -> pd.DataFrame:
    """
    Execute SQL directly without going through LLM
    Useful for debugging or when LLM fails
    
    Args:
        db: SQLDatabase connection
        sql_query: Raw SQL query
    
    Returns:
        Results as pandas DataFrame
    """
    try:
        logger.info(f"Executing SQL directly: {sql_query}")
        result = db.run(sql_query)
        logger.info("Query executed successfully")
        return result
    except Exception as e:
        logger.error(f"SQL execution failed: {e}")
        raise

# ============================================================================
# 5. MAIN EXECUTION
# ============================================================================

def main():
    """Main entry point"""
    
    print("""
    ======================================================================
         PostgreSQL + LangChain SQL Agent - Full Execution Pipeline
      User -> LLM -> SQL -> Executor -> Database -> Result -> Natural Answer
    ======================================================================
    """)
    
    logger.info("\n⚙️  SETUP REQUIREMENTS:")
    logger.info("  1. PostgreSQL running (check with pgAdmin4)")
    logger.info("  2. Ollama running: ollama serve")
    logger.info("  3. Model installed: ollama pull llama3.2:3b")
    logger.info("  4. Database has tables with sample data")
    
    try:
        test_with_sample_data()
    except Exception as e:
        logger.error(f"\n❌ Setup failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()