name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from GitHub Actions"
hii 
i am this side harshit sharma i make the new repo and i learn in that where i learn that git push origin , for the push the code , git commit 
