name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from GitHub Actions"
      - run: echo "This is a test workflow"
      - run: echo "You can add more steps here to run your tests"
      - run: echo "For example, you can run a Python script like this:"
      - run: python test/cleanpipelilne.py
      - run: echo "Tests completed"
      